services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    
    Harryn\Jacobn\ExtensionFrameworkBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Templates,Package}'
    
    Harryn\Jacobn\ExtensionFrameworkBundle\EventListener\Kernel:
        tags:
            - { name: kernel.event_listener, event: kernel.request }
            - { name: kernel.event_listener, event: kernel.controller_arguments }
    
    Harryn\Jacobn\ExtensionFrameworkBundle\EventListener\Console:
        tags:
            - { name: kernel.event_listener, event: console.command }
            - { name: kernel.event_listener, event: console.terminate }
    
    # Aliases
    uvdesk_extension.twig_loader:
        public: true
        alias: twig.loader
    
    uvdesk_extension.assets_manager:
        public: true
        alias: assets.packages
